<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Bookstore.Web.Tests</AssemblyName>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <RootNamespace>Bookstore.Web.Tests</RootNamespace>
    <StartupObject></StartupObject>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.runner.visualstudio" Version="*" />
    <PackageReference Include="xunit.runner.console" Version="*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="*" />
    <PackageReference Include="xunit.core" Version="2.9.3" />
    <PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
    <PackageReference Include="xunit.analyzers" Version="1.18.0" />
    <PackageReference Include="xunit.extensibility.execution" Version="2.9.3" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.abstractions" Version="2.0.3" />
    <PackageReference Include="xunit.assert" Version="2.9.3" />
    <PackageReference Include="Bookstore.Common" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Bookstore.Web/Bookstore.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
    <None Include="packages.config" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bookstore.Web\Bookstore.Web.csproj">
      <Project>{40e4e3fc-93f0-4cf2-a506-31546f7606c4}</Project>
      <Name>Bookstore.Web</Name>
    </ProjectReference>
  </ItemGroup>
</Project>