<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Bookstore.Domain.Tests</AssemblyName>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
    <OutputType>Exe</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <RootNamespace>Bookstore.Domain.Tests</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="xunit.core" Version="2.9.3" />
    <PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
    <PackageReference Include="xunit.analyzers" Version="1.18.0" />
    <PackageReference Include="xunit.extensibility.execution" Version="2.9.3" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.abstractions" Version="2.0.3" />
    <PackageReference Include="xunit.assert" Version="2.9.3" />
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="17.13.0" />
    <PackageReference Include="System.Collections.Immutable" Version="9.0.0" />
    <PackageReference Include="System.Reflection.Metadata" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Bookstore.Domain/Bookstore.Domain.csproj" />
    <ProjectReference Include="../Bookstore.Web/Bookstore.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
    <None Include="packages.config" />
  </ItemGroup>
  <ItemGroup>
    <Analyzer Include="..\..\packages\xunit.analyzers.1.18.0\analyzers\dotnet\cs\xunit.analyzers.dll" />
    <Analyzer Include="..\..\packages\xunit.analyzers.1.18.0\analyzers\dotnet\cs\xunit.analyzers.fixes.dll" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bookstore.Domain\Bookstore.Domain.csproj">
      <Project>{eceeb3cb-16c9-4358-a250-65837fe71243}</Project>
      <Name>Bookstore.Domain</Name>
    </ProjectReference>
    <ProjectReference Include="..\Bookstore.Web\Bookstore.Web.csproj">
      <Project>{40E4E3FC-93F0-4CF2-A506-31546F7606C4}</Project>
      <Name>Bookstore.Web</Name>
    </ProjectReference>
  </ItemGroup>
</Project>